apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-02-04T03:48:04Z"
  name: simplenode-canary
  resourceVersion: "81984"
  selfLink: /api/v1/namespaces/simpleproject-staging/services/simplenode
  uid: 25bd7eb1-4701-11ea-acbd-42010aa800ad
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: simplenode
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
